spring:
  security:
    oauth2:
      client:
        registration:
          # twitter:
          #   client-id: your-twitter-client-id
          #   client-secret: your-twitter-client-secret
          #   scope:
          #     - read:user
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - profile
              - email
          
          github:
            client-id: Ov23lilx1V6TDSzQQhd1
            client-secret: d1c183408b5b6bd8e9faa1373eebaac88ffd655c
            scope:
              - user:email
