spring:
  security:
    oauth2:
      client:
        registration:
          # twitter:
          #   client-id: your-twitter-client-id
          #   client-secret: your-twitter-client-secret
          #   scope:
          #     - read:user
          google:
            client-id: test_id
            client-secret: test_secret
            scope:
              - profile
              - email
          
          github:
            client-id: test_id
            client-secret: test_secret
            scope:
              - user:email
